VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "clsCustomer"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Public BillToCustomerName As String
Public BillToAddress As String
Public BillToTown As String
Public BillToState As String
Public BillToZipCode As String
Public BillToContactName As String
Public BillToPhoneNumber As String
Public BillToFaxNumber As String
Public BillToEmail As String
Public ShipToCustomerName As String
Public ShipToAddress As String
Public ShipToTown As String
Public ShipToState As String
Public ShipToZipCode As String
Public ShipToContactName As String
Public ShipToPhoneNumber As String
Public ShipToFaxNumber As String
Public ShipToEmail As String
Public ContractAwardNumber As String
Public CurrentPOPStartDate As String
Public CurrentPOPEndDate As String
Public NewPOPStartDate As String
Public NewPOPEndDate As String
Public QuoteInfoEmailAddress As String
Public QuoteInfoBillerFirstName As String
Public QuoteInfoBillerLastName As String
Public QuoteInfoDate As String
Public QuoteInfoAppendix As String
Public QuoteInfoBillersManagerName As String
Public QuoteInfoQuoteNumber As String
Public MeterAdmin As String
Public Model As String
Public Serial As String
Public Contract As String
Public MABase As String
Public RentalBase As String
Public Allowance As String
Public Meter As String
Public OverageRate As String
Public BaseBillFrequency As String
Public UsageBillFrequency As String
Public MeterName As String
Public CurrentRead As String
Public GroupContract As String
Public NumPeriods As String



